version: '3'
services:
  nginx:
    build: .
    ports:
      - "80:80"

  app1:
    build: app1
    volumes:
      - ./app1/:/app

  app2:
    build: app2
    volumes:
      - ./app2/:/app
    environment:
      - VIRTUAL_HOST=0.0.0.0



